//! The flecs declaration modules, and the list the guards walk.
//!
//! Every declaration used to live in this one file, which made it the largest
//! in the package by a factor of four and the one every area appended to.
//!
//! `modules` is the point of keeping it. `abi_check.zig` and
//! `abi_manifest.zig` discover what to check by walking it, so a module
//! added here is covered without either being told — and one NOT added here
//! is covered by neither. `api_tiers.zig` is generated by reading the same
//! modules, and says which of what they declare is flecs's API and which is
//! flecs's implementation.

pub const alerts = @import("c/alerts.zig");
pub const app = @import("c/app.zig");
pub const core = @import("c/core.zig");
pub const doc = @import("c/doc.zig");
pub const entity = @import("c/entity.zig");
pub const http = @import("c/http.zig");
pub const iter = @import("c/iter.zig");
pub const json = @import("c/json.zig");
pub const log = @import("c/log.zig");
pub const meta = @import("c/meta.zig");
pub const metrics = @import("c/metrics.zig");
pub const observer = @import("c/observer.zig");
pub const os = @import("c/os.zig");
pub const pipeline = @import("c/pipeline.zig");
pub const query = @import("c/query.zig");
pub const script = @import("c/script.zig");
pub const stats = @import("c/stats.zig");
pub const system = @import("c/system.zig");
pub const table = @import("c/table.zig");
pub const timer = @import("c/timer.zig");
pub const value = @import("c/value.zig");
pub const world = @import("c/world.zig");

/// Every module above. Walked by `abi_check.zig` and `abi_manifest.zig`.
pub const modules = .{
    alerts,
    app,
    core,
    doc,
    entity,
    http,
    iter,
    json,
    log,
    meta,
    metrics,
    observer,
    os,
    pipeline,
    query,
    script,
    stats,
    system,
    table,
    timer,
    value,
    world,
};
